version: "3"
services:
    pac:
        image: hsldymq/pac
        container_name: "pac"
        restart: always
        logging:
            driver: journald
            options:
                tag: pac
        volumes:
            - ./../pac.js:/var/www/pac/pac.js
        ports:
            - 10801:10801
